# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        default:
            filesystem:
                data_root: '%shootings_directory%'

    # configure resolvers
    resolvers :
        # setup the default resolver
        default :
            # use the default web path
            web_path : ~

    # your filter sets are defined here
    filter_sets :

        # use the default cache configuration
        cache : ~

        full: ~

        # Miniatures dans l'admin ?
        thumbnail:
            quality: 60
            filters:
                thumbnail: { size : [120, 120], mode : inset }
        # Miniatures dans l'admin ?
        mini:
            quality: 60
            filters:
                thumbnail: { size : [280, 280], mode : inset }
        # ?
        cover:
            quality: 80
            filters:
                thumbnail: { size : [2000, 1500], mode : inset }
        # SD, pour les sous-sites (maternité, ...)
        sd:
            quality: 80
            filters:
                thumbnail: { size : [1000, 1000], mode : inset }
        # HD, pour les sous-sites (maternité, ...)
        hd:
            quality: 80
            filters:
                thumbnail: { size : [2000, 2000], mode : inset }
        # Site front
        front:
            quality: 70
            filters:
                thumbnail: { size : [500, 700], mode : inset }
        # Instagram
        instagram:
            quality: 90
            filters:
                thumbnail:
                    size: [1080, 1350]
                    mode: inset
                background:
                    #Redéfini au runtime pour une taille dynamique sur le ratio instagram (4:5)
                    #size: [1080, 1350]
                    position: center
                    color: '#FFFFFF'
                censure_filter:
                    # Redéfini au runtime, position dans la Photo
                    #positions: ['500,500', '200,100']
                    size: 20
                    enabled: false
