<?php


namespace App\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CustomPhotosDisplayType extends AbstractType
{
    //public function buildForm(FormBuilderInterface $builder, array $options)
    //{
    //    parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    //}

    //public function getBlockPrefix()
    //{
    //    return 'custom_photos_display';
    //}

    //public function configureOptions(OptionsResolver $resolver)
    //{
    //    $resolver->setDefaults([
    //        'block_name' => 'custom_photos_display'
    //    ]);
    //}

    //public function getParent()
    //{
    //    return CollectionType::class;
    //}

    //public function buildView(FormView $view, FormInterface $form, array $options)
    //{
    //    parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    //}


}
